[package]
name = "interoptopusffi"
edition = "2021"
version.workspace = true
authors.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
interoptopus = "0.14.27"
rand = "0.9.0-alpha.2"
thiserror = "1.0.63"
