[package]
name = "quadromon"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.228", features = ["derive"] }
dirs = "6.0.0"
toml = "0.9.8"
regex = "1.12.2"
serde_json = "1.0.145"
crossterm = "0.29.0"
ratatui = "0.30.0-beta.0"
timer = "0.2.0"
chrono = "0.4.42"