[package]
name = "filewatcher"
version = "0.1.1"
edition = "2022"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
datastore = { path = "../../datastore"}
serde = "1.0.144"
serde_derive = "1.0.144"
crc32fast = "1.3.2"